import { Ionicons } from "@expo/vector-icons";
import { useFocusEffect, useLocalSearchParams, useRouter } from "expo-router";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { api } from "@/src/api/client";
import { makeStyles, useTheme } from "@/src/theme";
import type { Order, OrderStatus } from "@/src/types";
import React from "react";

const statuses: OrderStatus[] = ["Order Received", "Preparing", "Ready", "Completed"];

export default function OrderDetailScreen() {
  const router = useRouter(); const insets = useSafeAreaInsets(); const styles = useStyles(); const { colors } = useTheme(); const { id = "" } = useLocalSearchParams<{ id: string }>(); const [order, setOrder] = React.useState<Order | null>(null); const [loading, setLoading] = React.useState(true); const [error, setError] = React.useState<string | null>(null); const [confirming, setConfirming] = React.useState(false);
  const load = React.useCallback(async () => { try { setError(null); setOrder(await api.orderById(String(id))); } catch (value) { setError(value instanceof Error ? value.message : "Could not load this order."); } finally { setLoading(false); } }, [id]);
  useFocusEffect(React.useCallback(() => { void load(); const timer = setInterval(() => void load(), 15000); return () => clearInterval(timer); }, [load]));
  const confirmDelivery = () => { Alert.alert("Confirm delivery", "Have you received this order?", [{ text: "Not yet", style: "cancel" }, { text: "Yes, received", onPress: async () => { setConfirming(true); try { await api.confirmDelivery(String(id)); await load(); } catch (value) { setError(value instanceof Error ? value.message : "Could not confirm delivery."); } finally { setConfirming(false); } } }]); };
  if (loading) return <View style={styles.center}><ActivityIndicator size="large" color={colors.brandPrimary} /><Text style={styles.muted}>Loading order…</Text></View>;
  if (error || !order) return <View style={styles.center}><Ionicons name="cloud-offline-outline" size={38} color={colors.error} /><Text style={styles.errorText}>{error ?? "Order not found."}</Text><Pressable onPress={() => void load()}><Text style={styles.link}>Retry</Text></Pressable></View>;
  const current = Math.max(0, statuses.indexOf(order.status ?? "Order Received"));
  return <View style={[styles.root, { paddingTop: insets.top + 12 }]}><ScrollView contentContainerStyle={{ paddingBottom: insets.bottom + 30 }}><Pressable onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={22} color={colors.onSurface} /><Text style={styles.backText}>Order details</Text></Pressable><Text style={styles.eyebrow}>LIVE ORDER STATUS</Text><Text style={styles.title}>{order.orderId ?? id}</Text><Text style={styles.date}>{order.createdAt ? new Date(order.createdAt).toLocaleString() : "Recent order"}</Text><View style={styles.statusCard}>{statuses.map((status, index) => <View key={status} style={styles.statusRow}><View style={[styles.statusCircle, index <= current && { backgroundColor: colors.brandPrimary }]}>{index < current ? <Ionicons name="checkmark" size={16} color={colors.onBrandPrimary} /> : index === current ? <View style={styles.innerDot} /> : null}</View><View style={styles.statusCopy}><Text style={[styles.statusName, index === current && { color: colors.brandPrimary }]}>{status}</Text><Text style={styles.statusHint}>{index < current ? "Complete" : index === current ? "Happening now" : "Up next"}</Text></View>{index < statuses.length - 1 ? <View style={[styles.connector, index < current && { backgroundColor: colors.brandPrimary }]} /> : null}</View>)}</View><View style={styles.orderCard}><Text style={styles.cardTitle}>Your order</Text>{order.itemsOrdered?.map((item) => <View key={item.name} style={styles.line}><Text style={styles.item}>{item.quantity} × {item.name}</Text><Text style={styles.value}>₹{item.price * item.quantity}</Text></View>)}<View style={styles.totalLine}><Text style={styles.totalLabel}>Total</Text><Text style={styles.totalValue}>₹{order.totalAmount}</Text></View><Text style={styles.address}>{order.address}</Text></View>{order.status === "Completed" ? <Pressable onPress={() => router.push(`/review/${id}`)} style={styles.primary}><Ionicons name="star" size={18} color={colors.onBrandPrimary} /><Text style={styles.primaryText}>{order.rating ? "View your review" : "Rate your order"}</Text></Pressable> : <Pressable disabled={confirming || order.status !== "Ready"} onPress={confirmDelivery} style={[styles.primary, (confirming || order.status !== "Ready") && styles.disabled]}>{confirming ? <ActivityIndicator color={colors.onBrandPrimary} /> : <><Ionicons name="checkmark-circle-outline" size={18} color={colors.onBrandPrimary} /><Text style={styles.primaryText}>{order.status === "Ready" ? "Confirm delivery" : "Available when ready"}</Text></>}</Pressable>}</ScrollView></View>;
}

const useStyles = makeStyles((colors) => StyleSheet.create({ root: { flex: 1, backgroundColor: colors.surface, paddingHorizontal: 18 }, back: { minHeight: 44, flexDirection: "row", alignItems: "center", gap: 10 }, backText: { color: colors.onSurface, fontWeight: "800" }, eyebrow: { color: colors.brandPrimary, fontSize: 11, fontWeight: "900", letterSpacing: 1, marginTop: 24 }, title: { color: colors.onSurface, fontSize: 25, fontWeight: "900", marginTop: 7 }, date: { color: colors.muted, fontSize: 12, marginTop: 5 }, statusCard: { marginTop: 25, backgroundColor: colors.surfaceSecondary, borderRadius: 20, padding: 18 }, statusRow: { minHeight: 63, flexDirection: "row", alignItems: "flex-start", position: "relative" }, statusCircle: { width: 30, height: 30, borderRadius: 15, backgroundColor: colors.surfaceTertiary, alignItems: "center", justifyContent: "center", zIndex: 2 }, innerDot: { width: 9, height: 9, borderRadius: 5, backgroundColor: colors.onBrandPrimary }, statusCopy: { marginLeft: 13, paddingTop: 2 }, statusName: { color: colors.onSurfaceSecondary, fontWeight: "800", fontSize: 14 }, statusHint: { color: colors.muted, fontSize: 11, marginTop: 4 }, connector: { position: "absolute", width: 2, height: 36, left: 14, top: 28, backgroundColor: colors.borderStrong }, orderCard: { marginTop: 14, backgroundColor: colors.surfaceSecondary, borderRadius: 18, padding: 16 }, cardTitle: { color: colors.onSurface, fontWeight: "900", fontSize: 16, marginBottom: 10 }, line: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 6 }, item: { color: colors.onSurfaceSecondary, fontSize: 13 }, value: { color: colors.onSurfaceSecondary, fontSize: 13, fontWeight: "700" }, totalLine: { borderTopWidth: 1, borderTopColor: colors.border, marginTop: 8, paddingTop: 12, flexDirection: "row", justifyContent: "space-between" }, totalLabel: { color: colors.onSurface, fontSize: 16, fontWeight: "900" }, totalValue: { color: colors.brandPrimary, fontSize: 18, fontWeight: "900" }, address: { color: colors.muted, fontSize: 12, borderTopWidth: 1, borderTopColor: colors.border, marginTop: 12, paddingTop: 12 }, primary: { minHeight: 52, borderRadius: 15, backgroundColor: colors.brandPrimary, marginTop: 16, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8 }, primaryText: { color: colors.onBrandPrimary, fontWeight: "900", fontSize: 14 }, disabled: { opacity: 0.45 }, center: { flex: 1, backgroundColor: colors.surface, alignItems: "center", justifyContent: "center", padding: 25, gap: 12 }, muted: { color: colors.muted }, errorText: { color: colors.error, textAlign: "center" }, link: { color: colors.brandPrimary, fontWeight: "800" } }));