import { Ionicons } from "@expo/vector-icons";
import * as Linking from "expo-linking";
import { useLocalSearchParams, useRouter } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useApp } from "@/src/store/app-store";
import { makeStyles, useTheme } from "@/src/theme";

export default function SuccessScreen() {
  const router = useRouter(); const insets = useSafeAreaInsets(); const styles = useStyles(); const { colors } = useTheme(); const { orderId = "", prepTime = "10", customerName = "", address = "", total = "0" } = useLocalSearchParams<{ orderId: string; prepTime: string; customerName: string; phone: string; address: string; total: string }>(); const { refreshOrders } = useApp();
  const whatsapp = () => { const text = `Hi DSB Fast Food! My order ${orderId} is placed.\nName: ${customerName}\nTotal: ₹${total}\nAddress: ${address}\nPayment: Cash on Delivery`; void Linking.openURL(`https://wa.me/9321611315?text=${encodeURIComponent(text)}`); };
  return <View style={[styles.root, { paddingTop: insets.top + 24 }]}><ScrollView contentContainerStyle={styles.content}><View style={styles.check}><Ionicons name="checkmark" size={50} color={colors.onBrandPrimary} /></View><Text style={styles.eyebrow}>DSB FAST FOOD</Text><Text style={styles.title}>Order placed!</Text><Text style={styles.subtitle}>Your food is being prepared fresh for you.</Text><View style={styles.orderCard}><Text style={styles.orderLabel}>ORDER ID</Text><Text style={styles.orderId}>{orderId}</Text><View style={styles.divider} /><View style={styles.meta}><View><Text style={styles.metaLabel}>EST. PREP TIME</Text><Text style={styles.metaValue}>{prepTime} minutes</Text></View><View><Text style={styles.metaLabel}>PAYMENT</Text><Text style={styles.metaValue}>Cash on Delivery</Text></View></View></View><View style={styles.trackPreview}><View style={styles.trackIcon}><Ionicons name="restaurant-outline" size={21} color={colors.brandPrimary} /></View><View style={{ flex: 1 }}><Text style={styles.trackTitle}>Order received</Text><Text style={styles.trackText}>We’ll keep you posted as it moves through the kitchen.</Text></View><Ionicons name="chevron-forward" size={18} color={colors.muted} /></View><Pressable onPress={whatsapp} style={styles.whatsapp}><Ionicons name="logo-whatsapp" size={20} color={colors.success} /><Text style={styles.whatsappText}>Confirm on WhatsApp</Text></Pressable><Pressable onPress={() => { void refreshOrders(); router.replace(`/order/${orderId}`); }} style={styles.primary}><Text style={styles.primaryText}>Track order</Text><Ionicons name="arrow-forward" size={17} color={colors.onBrandPrimary} /></Pressable><Pressable onPress={() => { void refreshOrders(); router.replace("/(tabs)/orders"); }} style={styles.secondary}><Text style={styles.secondaryText}>View orders</Text></Pressable><Pressable onPress={() => router.replace("/(tabs)/menu")} style={styles.browse}><Text style={styles.browseText}>Continue browsing</Text></Pressable></ScrollView></View>;
}

const useStyles = makeStyles((colors) => StyleSheet.create({ root: { flex: 1, backgroundColor: colors.surface }, content: { paddingHorizontal: 20, alignItems: "center", paddingBottom: 30 }, check: { width: 88, height: 88, borderRadius: 44, backgroundColor: colors.success, alignItems: "center", justifyContent: "center", marginTop: 25 }, eyebrow: { color: colors.brandPrimary, letterSpacing: 1, fontSize: 11, fontWeight: "900", marginTop: 28 }, title: { color: colors.onSurface, fontSize: 31, fontWeight: "900", marginTop: 8 }, subtitle: { color: colors.muted, fontSize: 14, textAlign: "center", marginTop: 6 }, orderCard: { width: "100%", backgroundColor: colors.surfaceSecondary, borderRadius: 18, padding: 18, marginTop: 28, borderWidth: 1, borderColor: colors.border }, orderLabel: { color: colors.muted, fontSize: 10, fontWeight: "900", letterSpacing: 1 }, orderId: { color: colors.onSurface, fontSize: 20, fontWeight: "900", marginTop: 7 }, divider: { height: 1, backgroundColor: colors.border, marginVertical: 16 }, meta: { flexDirection: "row", justifyContent: "space-between" }, metaLabel: { color: colors.muted, fontSize: 10, fontWeight: "800" }, metaValue: { color: colors.onSurfaceSecondary, fontSize: 12, fontWeight: "800", marginTop: 5 }, trackPreview: { flexDirection: "row", alignItems: "center", width: "100%", padding: 14, marginTop: 14, backgroundColor: colors.brandTertiary, borderRadius: 15, gap: 10 }, trackIcon: { width: 40, height: 40, borderRadius: 20, backgroundColor: colors.surface, alignItems: "center", justifyContent: "center" }, trackTitle: { color: colors.onSurface, fontWeight: "900", fontSize: 13 }, trackText: { color: colors.onSurfaceTertiary, fontSize: 11, lineHeight: 16, marginTop: 3 }, primary: { width: "100%", minHeight: 52, borderRadius: 15, backgroundColor: colors.brandPrimary, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 10, marginTop: 17 }, primaryText: { color: colors.onBrandPrimary, fontWeight: "900", fontSize: 15 }, whatsapp: { width: "100%", minHeight: 48, borderRadius: 14, backgroundColor: colors.onSuccess, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8, marginTop: 16 }, whatsappText: { color: colors.success, fontWeight: "900", fontSize: 13 }, secondary: { width: "100%", minHeight: 48, borderRadius: 14, borderWidth: 1, borderColor: colors.borderStrong, alignItems: "center", justifyContent: "center", marginTop: 10 }, secondaryText: { color: colors.onSurface, fontWeight: "800" }, browse: { minHeight: 44, justifyContent: "center" }, browseText: { color: colors.muted, fontSize: 12, fontWeight: "800" } }));