import { Ionicons } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { api } from "@/src/api/client";
import { makeStyles, useTheme } from "@/src/theme";
import React from "react";

export default function ReviewScreen() {
  const router = useRouter(); const insets = useSafeAreaInsets(); const styles = useStyles(); const { colors } = useTheme(); const { id = "" } = useLocalSearchParams<{ id: string }>(); const [rating, setRating] = React.useState(5); const [review, setReview] = React.useState(""); const [submitting, setSubmitting] = React.useState(false); const [error, setError] = React.useState<string | null>(null); const [done, setDone] = React.useState(false);
  const submit = async () => { if (rating < 1 || rating > 5) { setError("Choose a rating from 1 to 5 stars."); return; } setSubmitting(true); setError(null); try { await api.rateOrder(String(id), rating, review.trim()); setDone(true); } catch (value) { setError(value instanceof Error ? value.message : "Could not submit your review."); } finally { setSubmitting(false); } };
  return <View style={[styles.root, { paddingTop: insets.top + 18 }]}><Pressable onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={22} color={colors.onSurface} /><Text style={styles.backText}>Review order</Text></Pressable>{done ? <View style={styles.done}><View style={styles.check}><Ionicons name="checkmark" size={38} color={colors.onBrandPrimary} /></View><Text style={styles.title}>Thanks for the love!</Text><Text style={styles.subtitle}>Your feedback helps DSB keep making every order better.</Text><Pressable onPress={() => router.replace("/(tabs)/orders")} style={styles.primary}><Text style={styles.primaryText}>Back to orders</Text></Pressable></View> : <><Text style={styles.eyebrow}>ORDER FEEDBACK</Text><Text style={styles.title}>How was your meal?</Text><Text style={styles.subtitle}>Tap a star to rate your DSB experience.</Text><View style={styles.stars}>{[1, 2, 3, 4, 5].map((value) => <Pressable key={value} accessibilityRole="button" accessibilityLabel={`${value} stars`} onPress={() => setRating(value)} style={styles.star}><Ionicons name={value <= rating ? "star" : "star-outline"} size={39} color={value <= rating ? colors.brandSecondary : colors.borderStrong} /></Pressable>)}</View><TextInput value={review} onChangeText={setReview} multiline maxLength={300} placeholder="Tell us what you loved (optional)" placeholderTextColor={colors.muted} style={styles.input} />{error ? <Text style={styles.error}>{error}</Text> : null}<Pressable onPress={() => void submit()} disabled={submitting} style={[styles.primary, submitting && { opacity: 0.6 }]}>{submitting ? <ActivityIndicator color={colors.onBrandPrimary} /> : <Text style={styles.primaryText}>Submit review</Text>}</Pressable></>}</View>;
}

const useStyles = makeStyles((colors) => StyleSheet.create({ root: { flex: 1, backgroundColor: colors.surface, paddingHorizontal: 20 }, back: { minHeight: 44, flexDirection: "row", alignItems: "center", gap: 10 }, backText: { color: colors.onSurface, fontWeight: "800" }, eyebrow: { color: colors.brandPrimary, fontSize: 11, fontWeight: "900", letterSpacing: 1, marginTop: 38 }, title: { color: colors.onSurface, fontWeight: "900", fontSize: 30, marginTop: 8 }, subtitle: { color: colors.muted, marginTop: 7, fontSize: 14, lineHeight: 21 }, stars: { flexDirection: "row", justifyContent: "center", marginVertical: 36, gap: 8 }, star: { minWidth: 44, minHeight: 44, alignItems: "center", justifyContent: "center" }, input: { height: 125, borderWidth: 1, borderColor: colors.border, borderRadius: 15, backgroundColor: colors.surfaceSecondary, padding: 14, color: colors.onSurface, textAlignVertical: "top", fontSize: 14 }, primary: { minHeight: 52, borderRadius: 15, backgroundColor: colors.brandPrimary, alignItems: "center", justifyContent: "center", marginTop: 17 }, primaryText: { color: colors.onBrandPrimary, fontWeight: "900", fontSize: 14 }, error: { color: colors.error, marginTop: 10, fontSize: 12 }, done: { alignItems: "center", marginTop: 100 }, check: { width: 78, height: 78, borderRadius: 39, backgroundColor: colors.success, alignItems: "center", justifyContent: "center" } }));