import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { FoodCard, ScreenTitle } from "@/src/components/ui";
import { categories } from "@/src/data/menu";
import { foodImages } from "@/src/data/images";
import { translate } from "@/src/i18n";
import { useApp } from "@/src/store/app-store";
import { makeStyles, useTheme } from "@/src/theme";

function isRestaurantOpen() { const hour = new Date().getHours(); return hour >= 11 && hour < 23; }

export default function HomeScreen() {
  const router = useRouter(); const insets = useSafeAreaInsets(); const { colors } = useTheme(); const styles = useStyles();
  const { language, menu, menuLoading, session } = useApp(); const open = isRestaurantOpen();
  return <View style={[styles.root, { paddingTop: insets.top + 16 }]}><ScrollView contentContainerStyle={{ paddingBottom: 32 }} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><View><Text style={styles.logo}>DSB <Text style={styles.logoAccent}>FAST FOOD</Text></Text><Text style={styles.location}><Ionicons name="location" size={13} color={colors.brandPrimary} /> {translate(language, "location")}</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Open profile" onPress={() => router.push("/(tabs)/profile")} style={styles.avatar}><Ionicons name={session ? "person" : "person-outline"} size={20} color={colors.brandPrimary} /></Pressable></View>
    <View style={styles.greeting}><Text style={styles.eyebrow}>HOT & SPICY · SINCE 2025</Text><Text style={styles.headline}>{translate(language, "hello")}</Text><Text style={styles.subline}>{translate(language, "delivery")}</Text></View>
    <View style={styles.hero}><Image source={{ uri: foodImages.noodles }} style={styles.heroImage} /><View style={styles.heroOverlay}><View style={[styles.statusPill, { backgroundColor: open ? colors.success : colors.error }]}><View style={styles.statusDot} /><Text style={styles.statusText}>{open ? translate(language, "open") : translate(language, "closed")}</Text></View><Text style={styles.heroTitle}>Street food{`\n`}with soul.</Text><Text style={styles.heroCopy}>{open ? "Fresh wok-fired favourites, ready when you are." : "We reopen at 11:00 AM. Plan your next craving."}</Text><Pressable accessibilityRole="button" onPress={() => router.push("/(tabs)/menu")} style={({ pressed }) => [styles.heroButton, pressed && { opacity: 0.8 }]}><Text style={styles.heroButtonText}>{translate(language, "orderNow")}</Text><Ionicons name="arrow-forward" size={17} color={colors.onBrandPrimary} /></Pressable></View></View>
    <View style={styles.infoRow}><View><Text style={styles.infoLabel}>{translate(language, "openHours")}</Text><Text style={styles.infoValue}>₹10 delivery · Min ₹50</Text></View><Ionicons name="flame" size={24} color={colors.brandPrimary} /></View>
    <ScreenTitle eyebrow="DSB FAVOURITES" title={translate(language, "popular")} right={<Pressable onPress={() => router.push("/(tabs)/menu")}><Text style={styles.link}>{translate(language, "browse")}</Text></Pressable>} />
    {menuLoading ? <Text style={styles.muted}>Loading today’s menu…</Text> : <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.horizontalCards}>{menu.slice(3, 6).map((item) => <FoodCard key={item.id} item={item} compact />)}</ScrollView>}
    <ScreenTitle eyebrow="FIND YOUR FAVOURITE" title={translate(language, "categories")} />
    <View style={styles.categoryGrid}>{categories.map((category, index) => <Pressable key={category} accessibilityRole="button" onPress={() => router.push({ pathname: "/(tabs)/menu", params: { category } })} style={({ pressed }) => [styles.category, pressed && { opacity: 0.76 }]}><View style={[styles.categoryIcon, { backgroundColor: [colors.brandTertiary, colors.surfaceTertiary, colors.brandTertiary, colors.surfaceTertiary][index] }]}><Ionicons name={index === 0 ? "restaurant" : index === 1 ? "fast-food" : index === 2 ? "flame" : "cafe"} size={22} color={colors.brandPrimary} /></View><Text style={styles.categoryText}>{category}</Text></Pressable>)}</View>
  </ScrollView></View>;
}

const useStyles = makeStyles((colors) => StyleSheet.create({ root: { flex: 1, backgroundColor: colors.surface, paddingHorizontal: 18 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, logo: { color: colors.onSurface, fontWeight: "900", fontSize: 20, letterSpacing: -0.5 }, logoAccent: { color: colors.brandPrimary }, location: { marginTop: 6, color: colors.muted, fontSize: 12 }, avatar: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.brandTertiary, alignItems: "center", justifyContent: "center" }, greeting: { marginTop: 30, marginBottom: 18 }, eyebrow: { color: colors.brandPrimary, fontSize: 11, fontWeight: "900", letterSpacing: 1 }, headline: { color: colors.onSurface, fontSize: 30, fontWeight: "900", marginTop: 7, letterSpacing: -0.7 }, subline: { color: colors.muted, marginTop: 7, fontSize: 14 }, hero: { height: 265, borderRadius: 24, overflow: "hidden", marginBottom: 14 }, heroImage: { width: "100%", height: "100%", position: "absolute" }, heroOverlay: { flex: 1, padding: 20, justifyContent: "flex-end", backgroundColor: "rgba(28,25,23,0.32)" }, statusPill: { alignSelf: "flex-start", borderRadius: 20, paddingHorizontal: 10, paddingVertical: 6, flexDirection: "row", alignItems: "center", marginBottom: 22 }, statusDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.onBrandPrimary, marginRight: 6 }, statusText: { color: colors.onBrandPrimary, fontSize: 10, fontWeight: "900" }, heroTitle: { color: colors.onBrandPrimary, fontSize: 30, lineHeight: 31, fontWeight: "900" }, heroCopy: { color: colors.onBrandPrimary, fontSize: 12, marginTop: 8, maxWidth: 230, lineHeight: 18 }, heroButton: { flexDirection: "row", alignItems: "center", gap: 8, alignSelf: "flex-start", marginTop: 15, backgroundColor: colors.brandPrimary, paddingHorizontal: 15, paddingVertical: 11, borderRadius: 12 }, heroButtonText: { color: colors.onBrandPrimary, fontSize: 13, fontWeight: "800" }, infoRow: { backgroundColor: colors.surfaceSecondary, borderRadius: 16, padding: 15, flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 30 }, infoLabel: { color: colors.onSurfaceSecondary, fontSize: 12, fontWeight: "700" }, infoValue: { color: colors.muted, marginTop: 4, fontSize: 12 }, link: { color: colors.brandPrimary, fontSize: 12, fontWeight: "800" }, muted: { color: colors.muted, marginVertical: 18 }, horizontalCards: { gap: 12, paddingVertical: 18 }, categoryGrid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", marginTop: 18 }, category: { width: "48%", flexDirection: "row", alignItems: "center", backgroundColor: colors.surfaceSecondary, borderRadius: 16, padding: 12, marginBottom: 12 }, categoryIcon: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center" }, categoryText: { color: colors.onSurface, fontSize: 14, fontWeight: "800", marginLeft: 10 } }));