import { Ionicons } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { FlatList, Pressable, RefreshControl, StyleSheet, Text, TextInput, View } from "react-native";
import React from "react";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { FoodCard, ScreenTitle } from "@/src/components/ui";
import { categories } from "@/src/data/menu";
import { translate } from "@/src/i18n";
import { useApp } from "@/src/store/app-store";
import { makeStyles, useTheme } from "@/src/theme";
import type { Category } from "@/src/types";

export default function MenuScreen() {
  const insets = useSafeAreaInsets(); const router = useRouter(); const params = useLocalSearchParams<{ category?: string }>(); const { colors } = useTheme(); const styles = useStyles();
  const { language, menu, menuLoading, menuError, refreshMenu } = useApp(); const [category, setCategory] = React.useState<Category | "All">((params.category as Category) || "All"); const [search, setSearch] = React.useState("");
  const filtered = menu.filter((item) => (category === "All" || item.category === category) && item.name.toLowerCase().includes(search.toLowerCase()));
  return <View style={[styles.root, { paddingTop: insets.top + 18 }]}><FlatList data={filtered} numColumns={2} keyExtractor={(item) => item.id} columnWrapperStyle={styles.columns} contentContainerStyle={{ paddingBottom: 30 }} refreshControl={<RefreshControl refreshing={menuLoading} onRefresh={refreshMenu} tintColor={colors.brandPrimary} />} ListHeaderComponent={<View><View style={styles.topRow}><View><Text style={styles.eyebrow}>DSB FAST FOOD</Text><Text style={styles.title}>{translate(language, "menu")}</Text></View><Pressable onPress={() => router.push("/(tabs)/cart")} style={styles.bag}><Ionicons name="bag-handle-outline" size={21} color={colors.brandPrimary} /></Pressable></View><View style={styles.search}><Ionicons name="search" size={18} color={colors.muted} /><TextInput value={search} onChangeText={setSearch} placeholder="Search dishes" placeholderTextColor={colors.muted} style={styles.searchInput} accessibilityLabel="Search dishes" /></View><FlatList horizontal showsHorizontalScrollIndicator={false} data={["All", ...categories]} keyExtractor={(item) => item} contentContainerStyle={styles.chips} renderItem={({ item }) => <Pressable onPress={() => setCategory(item as Category | "All")} style={[styles.chip, category === item && styles.activeChip]}><Text style={[styles.chipText, category === item && styles.activeChipText]}>{item}</Text></Pressable>} /><ScreenTitle eyebrow="FRESH FROM THE WOK" title={category === "All" ? "All dishes" : category} />{menuError ? <Pressable onPress={refreshMenu} style={styles.error}><Ionicons name="cloud-offline-outline" size={20} color={colors.error} /><Text style={styles.errorText}>{menuError} · {translate(language, "retry")}</Text></Pressable> : null}</View>} ListEmptyComponent={<View style={styles.empty}><Ionicons name="restaurant-outline" size={40} color={colors.brandPrimary} /><Text style={styles.emptyTitle}>{menuLoading ? translate(language, "loading") : "No dishes found"}</Text><Text style={styles.emptyText}>Try another category or search.</Text></View>} renderItem={({ item }) => <FoodCard item={item} />} /></View>;
}

const useStyles = makeStyles((colors) => StyleSheet.create({ root: { flex: 1, backgroundColor: colors.surface, paddingHorizontal: 18 }, topRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 18 }, eyebrow: { color: colors.brandPrimary, fontSize: 11, fontWeight: "900", letterSpacing: 1 }, title: { color: colors.onSurface, fontSize: 30, fontWeight: "900", marginTop: 4 }, bag: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.brandTertiary, alignItems: "center", justifyContent: "center" }, search: { height: 48, flexDirection: "row", alignItems: "center", borderWidth: 1, borderColor: colors.border, borderRadius: 14, paddingHorizontal: 14, backgroundColor: colors.surfaceSecondary }, searchInput: { flex: 1, marginLeft: 9, color: colors.onSurface, fontSize: 14 }, chips: { gap: 8, paddingVertical: 20 }, chip: { borderRadius: 999, backgroundColor: colors.surfaceSecondary, paddingHorizontal: 16, paddingVertical: 10 }, activeChip: { backgroundColor: colors.brandPrimary }, chipText: { color: colors.onSurfaceSecondary, fontSize: 12, fontWeight: "800" }, activeChipText: { color: colors.onBrandPrimary }, columns: { justifyContent: "space-between" }, error: { flexDirection: "row", gap: 8, backgroundColor: colors.onError, borderRadius: 12, padding: 12, marginVertical: 14, alignItems: "center" }, errorText: { color: colors.error, fontSize: 12, flex: 1 }, empty: { alignItems: "center", paddingVertical: 80 }, emptyTitle: { color: colors.onSurface, fontWeight: "800", fontSize: 17, marginTop: 12 }, emptyText: { color: colors.muted, marginTop: 6 } }));