import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { ScreenTitle } from "@/src/components/ui";
import { translate } from "@/src/i18n";
import { useApp } from "@/src/store/app-store";
import { makeStyles, useTheme } from "@/src/theme";
import type { Order } from "@/src/types";

const statuses = ["Order Received", "Preparing", "Ready", "Completed"] as const;

function OrderCard({ order }: { order: Order }) {
  const router = useRouter(); const { colors } = useTheme(); const styles = useStyles(); const status = order.status ?? "Order Received"; const current = Math.max(0, statuses.indexOf(status)); const id = order.orderId ?? order._id ?? order.id ?? "";
  return <Pressable accessibilityRole="button" onPress={() => router.push(`/order/${id}`)} style={({ pressed }) => [styles.card, pressed && { opacity: 0.8 }]}><View style={styles.cardTop}><View><Text style={styles.orderId}>{id}</Text><Text style={styles.orderDate}>{order.createdAt ? new Date(order.createdAt).toLocaleString() : "Recent order"}</Text></View><View style={styles.totalBadge}><Text style={styles.totalText}>₹{order.totalAmount}</Text></View></View><View style={styles.items}>{order.itemsOrdered?.map((item) => <Text key={item.name} style={styles.itemLine}>{item.quantity} × {item.name}</Text>)}</View><View style={styles.progress}>{statuses.map((item, index) => <View key={item} style={styles.progressItem}><View style={[styles.dot, index <= current && { backgroundColor: colors.brandPrimary }]}>{index < current ? <Ionicons name="checkmark" size={11} color={colors.onBrandPrimary} /> : null}</View>{index < statuses.length - 1 ? <View style={[styles.line, index < current && { backgroundColor: colors.brandPrimary }]} /> : null}</View>)}</View><View style={styles.statusLabels}>{statuses.map((item, index) => <Text key={item} style={[styles.statusLabel, index === current && { color: colors.brandPrimary, fontWeight: "900" }]}>{item === "Order Received" ? "Received" : item}</Text>)}</View><View style={styles.cardBottom}><Text style={styles.statusText}>{status}</Text>{status === "Completed" && !order.rating ? <Text style={styles.rate}>Rate order →</Text> : null}</View></Pressable>;
}

export default function OrdersScreen() {
  const router = useRouter(); const insets = useSafeAreaInsets(); const styles = useStyles(); const { colors } = useTheme(); const { language, session, orders, ordersLoading, ordersError, refreshOrders } = useApp();
  return <View style={[styles.root, { paddingTop: insets.top + 18 }]}><ScrollView contentContainerStyle={{ paddingBottom: 30 }} refreshControl={undefined}><ScreenTitle eyebrow="YOUR DSB JOURNEY" title={translate(language, "ordersTitle")} />{!session ? <View style={styles.empty}><View style={styles.emptyIcon}><Ionicons name="receipt-outline" size={36} color={colors.brandPrimary} /></View><Text style={styles.emptyTitle}>{translate(language, "signIn")}</Text><Text style={styles.emptyText}>{translate(language, "loginToSee")}</Text><Pressable onPress={() => router.push("/auth/phone")} style={styles.primary}><Text style={styles.primaryText}>{translate(language, "continueText")}</Text></Pressable></View> : ordersLoading ? <View style={styles.loading}><ActivityIndicator color={colors.brandPrimary} size="large" /><Text style={styles.emptyText}>{translate(language, "loading")}</Text></View> : ordersError ? <View style={styles.error}><Ionicons name="cloud-offline-outline" size={30} color={colors.error} /><Text style={styles.emptyText}>{ordersError}</Text><Pressable onPress={refreshOrders}><Text style={styles.rate}>{translate(language, "retry")}</Text></Pressable></View> : orders.length === 0 ? <View style={styles.empty}><View style={styles.emptyIcon}><Ionicons name="receipt-outline" size={36} color={colors.brandPrimary} /></View><Text style={styles.emptyTitle}>{translate(language, "noOrders")}</Text><Text style={styles.emptyText}>{translate(language, "orderFirst")}</Text><Pressable onPress={() => router.push("/(tabs)/menu")} style={styles.primary}><Text style={styles.primaryText}>{translate(language, "orderNow")}</Text></Pressable></View> : <View style={styles.list}>{orders.map((order) => <OrderCard key={order.orderId ?? order._id ?? order.id} order={order} />)}</View>}</ScrollView></View>;
}

const useStyles = makeStyles((colors) => StyleSheet.create({ root: { flex: 1, backgroundColor: colors.surface, paddingHorizontal: 18 }, list: { marginTop: 24, gap: 14 }, card: { backgroundColor: colors.surfaceSecondary, borderRadius: 20, padding: 16, borderWidth: 1, borderColor: colors.border }, cardTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, orderId: { color: colors.onSurface, fontWeight: "900", fontSize: 15 }, orderDate: { color: colors.muted, fontSize: 11, marginTop: 4 }, totalBadge: { backgroundColor: colors.brandTertiary, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 7 }, totalText: { color: colors.brandPrimary, fontWeight: "900" }, items: { marginTop: 14, borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 12, gap: 5 }, itemLine: { color: colors.onSurfaceSecondary, fontSize: 13 }, progress: { flexDirection: "row", alignItems: "center", marginTop: 18 }, progressItem: { flexDirection: "row", alignItems: "center", flex: 1 }, dot: { width: 22, height: 22, borderRadius: 11, backgroundColor: colors.surfaceTertiary, alignItems: "center", justifyContent: "center" }, line: { height: 2, flex: 1, backgroundColor: colors.borderStrong }, statusLabels: { flexDirection: "row", justifyContent: "space-between", marginTop: 6 }, statusLabel: { color: colors.muted, fontSize: 9 }, cardBottom: { flexDirection: "row", justifyContent: "space-between", marginTop: 16, alignItems: "center" }, statusText: { color: colors.brandPrimary, fontSize: 12, fontWeight: "900" }, rate: { color: colors.brandPrimary, fontWeight: "800", fontSize: 12 }, empty: { alignItems: "center", paddingVertical: 90 }, emptyIcon: { width: 78, height: 78, borderRadius: 39, backgroundColor: colors.brandTertiary, alignItems: "center", justifyContent: "center" }, emptyTitle: { color: colors.onSurface, fontSize: 19, fontWeight: "900", marginTop: 16, textAlign: "center" }, emptyText: { color: colors.muted, marginTop: 8, textAlign: "center", maxWidth: 260, lineHeight: 19 }, primary: { minHeight: 50, minWidth: 150, paddingHorizontal: 20, marginTop: 20, borderRadius: 14, backgroundColor: colors.brandPrimary, alignItems: "center", justifyContent: "center" }, primaryText: { color: colors.onBrandPrimary, fontWeight: "900" }, loading: { alignItems: "center", paddingVertical: 100, gap: 16 }, error: { alignItems: "center", paddingVertical: 80, gap: 12 } }));