import { Ionicons } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { api } from "@/src/api/client";
import { translate } from "@/src/i18n";
import { useApp } from "@/src/store/app-store";
import { makeStyles, useTheme } from "@/src/theme";
import React from "react";

export default function OtpScreen() {
  const router = useRouter(); const { phone = "", returnTo = "/(tabs)/profile", devOtp: initialDevOtp } = useLocalSearchParams<{ phone: string; returnTo?: string; devOtp?: string }>(); const insets = useSafeAreaInsets(); const styles = useStyles(); const { colors } = useTheme(); const { language, login } = useApp(); const [otp, setOtp] = React.useState(""); const [devOtp, setDevOtp] = React.useState<string | null>(initialDevOtp ? String(initialDevOtp) : null); const [seconds, setSeconds] = React.useState(30); const [loading, setLoading] = React.useState(false); const [error, setError] = React.useState<string | null>(null);
  React.useEffect(() => { if (seconds <= 0) return undefined; const timer = setInterval(() => setSeconds((value) => value - 1), 1000); return () => clearInterval(timer); }, [seconds]);
  const verify = async () => { if (!/^\d{4,6}$/.test(otp)) { setError("Enter the OTP sent to your phone."); return; } setLoading(true); setError(null); try { const session = await api.verifyOtp(String(phone), otp); if (!session.token || !session.user) throw new Error("That OTP was not accepted."); await login(session); router.replace(returnTo as never); } catch (value) { setError(value instanceof Error ? value.message : "Invalid OTP. Please try again."); } finally { setLoading(false); } };
  const resend = async () => { if (seconds > 0) return; setError(null); try { const result = await api.sendOtp(String(phone)); setDevOtp(result.devOtp ?? null); setSeconds(30); } catch (value) { setError(value instanceof Error ? value.message : "Could not resend OTP."); } };
  return <KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : "height"} style={styles.root}><View style={[styles.content, { paddingTop: insets.top + 18 }]}><Pressable onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={22} color={colors.onSurface} /></Pressable><View style={styles.icon}><Ionicons name="shield-checkmark-outline" size={34} color={colors.brandPrimary} /></View><Text style={styles.eyebrow}>{translate(language, "otpSent").toUpperCase()}</Text><Text style={styles.title}>Check your phone.</Text><Text style={styles.subtitle}>Enter the 4–6 digit code sent to <Text style={styles.strong}>+91 {phone}</Text>.</Text><Text style={styles.label}>Verification code</Text><TextInput value={otp} onChangeText={setOtp} keyboardType="number-pad" maxLength={6} placeholder="••••••" placeholderTextColor={colors.muted} style={styles.input} autoFocus textContentType="oneTimeCode" />{devOtp ? <Pressable testID="dev-otp-hint" onPress={() => setOtp(devOtp)} style={styles.devHint}><Ionicons name="flask-outline" size={15} color={colors.warning} /><Text style={styles.devHintText}>Test mode · your OTP is <Text style={styles.devHintCode}>{devOtp}</Text> — tap to fill</Text></Pressable> : null}<Pressable onPress={() => void verify()} disabled={loading} style={[styles.primary, loading && { opacity: 0.6 }]}>{loading ? <ActivityIndicator color={colors.onBrandPrimary} /> : <><Text style={styles.primaryText}>{translate(language, "verify")}</Text><Ionicons name="arrow-forward" size={18} color={colors.onBrandPrimary} /></>}</Pressable>{error ? <Text style={styles.error}>{error}</Text> : null}<Pressable disabled={seconds > 0} onPress={() => void resend()} style={styles.resend}><Text style={[styles.resendText, seconds > 0 && { color: colors.muted }]}>{seconds > 0 ? `Resend in ${seconds}s` : translate(language, "resend")}</Text></Pressable></View></KeyboardAvoidingView>;
}

const useStyles = makeStyles((colors) => StyleSheet.create({ root: { flex: 1, backgroundColor: colors.surface }, content: { flex: 1, paddingHorizontal: 22 }, back: { width: 44, height: 44, justifyContent: "center" }, icon: { width: 70, height: 70, borderRadius: 22, backgroundColor: colors.brandTertiary, alignItems: "center", justifyContent: "center", marginTop: 35 }, eyebrow: { color: colors.brandPrimary, fontWeight: "900", fontSize: 11, letterSpacing: 1, marginTop: 32 }, title: { color: colors.onSurface, fontSize: 30, fontWeight: "900", marginTop: 8 }, subtitle: { color: colors.muted, fontSize: 14, lineHeight: 21, marginTop: 8, marginBottom: 35 }, strong: { color: colors.onSurface, fontWeight: "800" }, label: { color: colors.onSurfaceSecondary, fontWeight: "800", fontSize: 12, marginBottom: 8 }, input: { height: 58, borderWidth: 1, borderColor: colors.brandPrimary, borderRadius: 14, backgroundColor: colors.surfaceSecondary, textAlign: "center", color: colors.onSurface, fontSize: 24, letterSpacing: 12 }, primary: { marginTop: 22, minHeight: 54, borderRadius: 15, backgroundColor: colors.brandPrimary, flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 10 }, primaryText: { color: colors.onBrandPrimary, fontWeight: "900", fontSize: 15 }, error: { color: colors.error, textAlign: "center", marginTop: 12, fontSize: 12 }, devHint: { flexDirection: "row", alignItems: "center", gap: 7, marginTop: 12, padding: 11, borderRadius: 12, backgroundColor: colors.onWarning, minHeight: 44 }, devHintText: { color: colors.warning, fontSize: 12, flex: 1 }, devHintCode: { fontWeight: "900", letterSpacing: 2 }, resend: { minHeight: 44, alignItems: "center", justifyContent: "center", marginTop: 10 }, resendText: { color: colors.brandPrimary, fontWeight: "800", fontSize: 13 } }));