import { Ionicons } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { api } from "@/src/api/client";
import { translate } from "@/src/i18n";
import { useApp } from "@/src/store/app-store";
import { makeStyles, useTheme } from "@/src/theme";
import React from "react";

export default function PhoneAuthScreen() {
  const router = useRouter(); const { returnTo } = useLocalSearchParams<{ returnTo?: string }>(); const insets = useSafeAreaInsets(); const styles = useStyles(); const { colors } = useTheme(); const { language } = useApp(); const [phone, setPhone] = React.useState(""); const [loading, setLoading] = React.useState(false); const [error, setError] = React.useState<string | null>(null);
  const send = async () => { if (!/^\d{10}$/.test(phone)) { setError("Enter a valid 10-digit phone number."); return; } setLoading(true); setError(null); try { await api.sendOtp(phone); router.push({ pathname: "/auth/otp", params: { phone, returnTo: returnTo ?? "/(tabs)/profile" } }); } catch (value) { setError(value instanceof Error ? value.message : "Could not send OTP. Please try again."); } finally { setLoading(false); } };
  return <KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : "height"} style={styles.root}><View style={[styles.content, { paddingTop: insets.top + 18 }]}><Pressable onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={22} color={colors.onSurface} /></Pressable><View style={styles.icon}><Ionicons name="phone-portrait-outline" size={34} color={colors.brandPrimary} /></View><Text style={styles.eyebrow}>WELCOME TO DSB</Text><Text style={styles.title}>{translate(language, "signIn")}</Text><Text style={styles.subtitle}>We’ll send a one-time code to verify your number.</Text><Text style={styles.label}>{translate(language, "phone")}</Text><View style={styles.phoneRow}><Text style={styles.prefix}>+91</Text><TextInput value={phone} onChangeText={setPhone} keyboardType="phone-pad" maxLength={10} placeholder="98765 43210" placeholderTextColor={colors.muted} style={styles.input} autoFocus /></View>{error ? <Text style={styles.error}>{error}</Text> : null}<Pressable onPress={() => void send()} disabled={loading} style={[styles.primary, loading && { opacity: 0.6 }]}>{loading ? <ActivityIndicator color={colors.onBrandPrimary} /> : <><Text style={styles.primaryText}>{translate(language, "sendOtp")}</Text><Ionicons name="arrow-forward" size={18} color={colors.onBrandPrimary} /></>}</Pressable><Text style={styles.footnote}>By continuing, you agree to receive a verification SMS.</Text></View></KeyboardAvoidingView>;
}

const useStyles = makeStyles((colors) => StyleSheet.create({ root: { flex: 1, backgroundColor: colors.surface }, content: { flex: 1, paddingHorizontal: 22 }, back: { width: 44, height: 44, justifyContent: "center" }, icon: { width: 70, height: 70, borderRadius: 22, backgroundColor: colors.brandTertiary, alignItems: "center", justifyContent: "center", marginTop: 35 }, eyebrow: { color: colors.brandPrimary, fontWeight: "900", fontSize: 11, letterSpacing: 1, marginTop: 32 }, title: { color: colors.onSurface, fontSize: 30, fontWeight: "900", marginTop: 8 }, subtitle: { color: colors.muted, fontSize: 14, lineHeight: 21, marginTop: 8, marginBottom: 35 }, label: { color: colors.onSurfaceSecondary, fontWeight: "800", fontSize: 12, marginBottom: 8 }, phoneRow: { flexDirection: "row", borderWidth: 1, borderColor: colors.border, borderRadius: 14, backgroundColor: colors.surfaceSecondary, alignItems: "center", paddingLeft: 15 }, prefix: { color: colors.onSurfaceSecondary, fontWeight: "800", fontSize: 15, borderRightWidth: 1, borderRightColor: colors.border, paddingRight: 12 }, input: { flex: 1, height: 52, paddingHorizontal: 13, color: colors.onSurface, fontSize: 17, letterSpacing: 1 }, error: { color: colors.error, marginTop: 10, fontSize: 12 }, primary: { marginTop: 22, minHeight: 54, borderRadius: 15, backgroundColor: colors.brandPrimary, flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 10 }, primaryText: { color: colors.onBrandPrimary, fontWeight: "900", fontSize: 15 }, footnote: { textAlign: "center", color: colors.muted, fontSize: 11, marginTop: 18, lineHeight: 17 } }));