import { Ionicons } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { QuantityStepper } from "@/src/components/ui";
import { translate } from "@/src/i18n";
import { useApp } from "@/src/store/app-store";
import { makeStyles, useTheme } from "@/src/theme";
import React from "react";

export default function ProductScreen() {
  const router = useRouter(); const { id } = useLocalSearchParams<{ id: string }>(); const insets = useSafeAreaInsets(); const styles = useStyles(); const { colors } = useTheme(); const { menu, language, addToCart, selectedBranch, canOrder } = useApp(); const item = menu.find((entry) => entry.id === id); const [quantity, setQuantity] = React.useState(1);
  if (!item) return <View style={styles.notFound}><Text style={styles.title}>Dish not found</Text><Pressable onPress={() => router.back()}><Text style={styles.link}>Go back</Text></Pressable></View>;
  const add = () => { if (!canOrder || item.soldOut) return; for (let index = 0; index < quantity; index += 1) addToCart(item); router.push("/(tabs)/cart"); };
  const unavailable = item.soldOut || !canOrder;
  return <View style={[styles.root, { paddingTop: insets.top }]}><ScrollView contentContainerStyle={{ paddingBottom: insets.bottom + 24 }}><Pressable onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={22} color={colors.onSurface} /></Pressable><Image source={{ uri: item.image }} style={styles.image} /><View style={styles.content}><View style={styles.category}><Text style={styles.categoryText}>{selectedBranch?.name ?? item.category}</Text>{item.soldOut ? <Text style={styles.soldOut}>{translate(language, "soldOut")}</Text> : !canOrder ? <Text style={styles.soldOut}>COMING SOON</Text> : null}</View><Text style={styles.title}>{item.name}</Text><Text style={styles.price}>₹{item.price}</Text><Text style={styles.description}>{item.description} Made fresh at DSB Fast Food with our signature hot-and-spicy seasoning.</Text><View style={styles.details}><View><Text style={styles.detailLabel}>Freshly cooked</Text><Text style={styles.detailValue}>Made to order</Text></View><View><Text style={styles.detailLabel}>Delivery</Text><Text style={styles.detailValue}>{selectedBranch?.deliveryCharge !== undefined ? `₹${selectedBranch.deliveryCharge} flat fee` : "Available at launch"}</Text></View></View><Text style={styles.quantityLabel}>Quantity</Text><View style={styles.bottomRow}><QuantityStepper quantity={quantity} onChange={(value) => setQuantity(Math.max(1, value))} /><Pressable disabled={unavailable} onPress={add} style={[styles.primary, unavailable && styles.disabled]}><Text style={styles.primaryText}>{item.soldOut ? translate(language, "soldOut") : !canOrder ? "Coming soon" : `${translate(language, "add")} · ₹${item.price * quantity}`}</Text></Pressable></View></View></ScrollView></View>;
}

const useStyles = makeStyles((colors) => StyleSheet.create({ root: { flex: 1, backgroundColor: colors.surface }, back: { width: 44, height: 44, marginLeft: 18, alignItems: "center", justifyContent: "center" }, image: { width: "100%", height: 285, marginTop: 4 }, content: { padding: 20 }, category: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, categoryText: { color: colors.brandPrimary, fontSize: 12, fontWeight: "900", letterSpacing: 1 }, soldOut: { color: colors.error, backgroundColor: colors.onError, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 5, fontSize: 10, fontWeight: "900" }, title: { color: colors.onSurface, fontSize: 30, fontWeight: "900", marginTop: 10 }, price: { color: colors.brandPrimary, fontSize: 21, fontWeight: "900", marginTop: 8 }, description: { color: colors.muted, fontSize: 15, lineHeight: 23, marginTop: 17 }, details: { flexDirection: "row", justifyContent: "space-between", borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.border, marginTop: 25, paddingVertical: 16 }, detailLabel: { color: colors.muted, fontSize: 11 }, detailValue: { color: colors.onSurfaceSecondary, fontWeight: "800", fontSize: 13, marginTop: 5 }, quantityLabel: { color: colors.onSurface, fontWeight: "900", marginTop: 26, marginBottom: 10 }, bottomRow: { flexDirection: "row", alignItems: "center", gap: 12 }, primary: { flex: 1, minHeight: 50, borderRadius: 14, backgroundColor: colors.brandPrimary, alignItems: "center", justifyContent: "center" }, primaryText: { color: colors.onBrandPrimary, fontWeight: "900", fontSize: 14 }, disabled: { opacity: 0.45 }, notFound: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: colors.surface }, link: { color: colors.brandPrimary, marginTop: 12, fontWeight: "800" } }));